config/routes.rb
Rails.application.routes.draw do
  root :to => 'requests#index'
  resources :requests
  post 'requests/parse_json', :to => 'requests#parse_json'
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	def index
		@requests = Request.paginate(page: params[:page])
	end

	def parse_json
		@request = Request.new request_params

		if @request.save
			respond_to do |format|
				format.html
				format.json { render json: @request, status: :ok }
			end
		end
	end

	def show
		@request = Request.find params[:id]
	end

	private
		def request_params
			params[:request_number] = params[:RequestNumber]
			params[:sequence_number] = params[:SequenceNumber]
			params[:request_type] = params[:RequestType]
			params[:service_area_primary_service_area_code] = params[:ServiceArea][:PrimaryServiceAreaCode]
			params[:service_area_additional_service_area_codes] = params[:ServiceArea][:AdditionalServiceAreaCodes]
			params[:excavator_company_name] = params[:Excavator][:CompanyName]
			params[:excavator_address] = params[:Excavator][:Address]
			params[:digsite_info_well_known_text] = params[:ExcavationInfo][:DigsiteInfo][:WellKnownText]
			params.permit(
				:request_number,
				:sequence_number,
				:request_type,
				:service_area_primary_service_area_code,
				:service_area_additional_service_area_codes,
				:excavator_company_name,
				:excavator_address,
				:digsite_info_well_known_text
			)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/index.html.erb
<div class="alert alert-success hide"></div>
<div class="form-group">
	<%= link_to "Parse JSON", '#', :data => {url: requests_parse_json_path}, :id => 'parse_json', :class => 'btn btn-primary' %>
</div>

<%= will_paginate %>

<table class="table table-striped">
	<tr>
		<th>Request Number</th>
		<th>Sequence Number</th>
		<th>Request Action</th>
		<th>Primary Service Area Code</th>
		<th>Additional Service Area Codes</th>
		<th>Company Name</th>
		<th>Address</th>
		<th>Digsite Info Well Known Text</th>
	</tr>
	<% @requests.each do |request| %>
	<tr>
		<td><%= link_to request.request_number, request %></td>
		<td><%= request.sequence_number %></td>
		<td><%= request.request_type %></td>
		<td><%= request.service_area_primary_service_area_code %></td>
		<td><%= request.service_area_additional_service_area_codes %></td>
		<td><%= request.excavator_company_name %></td>
		<td><%= request.excavator_address %></td>
		<td><%= request.digsite_info_well_known_text %></td>
	</tr>
	<% end %>

<%= will_paginate %>

<script>
$(function(){
	$('#parse_json').on('click', function(element){
		var url = $(this).data('url');
		$.ajax({
			type: 'GET',
			url: 'data.json',
			dataType: 'json'
		}).done(function(json){
			$.ajax({
				type: 'POST',
				dataType: 'JSON',
				url: url,
				data: json
			}).done(function(data) {
				$('.alert.alert-success').removeClass('hide');
				$('.alert.alert-success').text('The json data was successfully parsed.');
				window.location.href = '<%= root_path %>';
				console.log(data);
			}).fail(function(jqXHR, textStatus){
				console.log(textStatus);
			});
			console.log('success');
		}).fail(function(jqXHR, textStatus){
			console.log(textStatus);
		});
		return false;
	});
});
</script>

app/views/requests/show.html.erb
<ul class="form-group">
	<li>
		<p>Request Number</p>
		<%= @request.request_number %>
	</li>
	<li>
		<p>Sequence Number</p>
		<%= @request.sequence_number %>
	</li>
	<li>
		<p>Request Type</p>
		<%= @request.request_type %>
	</li>
	<li>
		<p>Primary Service Area Code</p>
		<%= @request.service_area_primary_service_area_code %>
	</li>
	<li>
		<p>Additional Service Area Codes</p>
		<%= @request.service_area_additional_service_area_codes %>
	</li>
	<li>
		<p>Company Name</p>
		<%= @request.excavator_company_name %>
	</li>
	<li>
		<p>Address</p>
		<%= @request.excavator_address %>
	</li>
	<li>
		<p>Digsite Info Well Known Text</p>
		<%= @request.digsite_info_well_known_text %>
	</li>
</ul>